# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 19:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mode', models.IntegerField(choices=[(1, 'Disabled'), (2, 'Enabled')], default=1)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='NodeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('mode', models.IntegerField(choices=[(1, 'Disabled'), (2, 'Enabled')], default=1)),
                ('action', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=1)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_actions', to='automated_workflow.Node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('mode', models.IntegerField(choices=[(1, 'Disabled'), (2, 'Enabled')], default=1)),
                ('rule', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('action_timedelta', models.DurationField()),
                ('pull_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_rules', to='automated_workflow.Node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Processing'), (3, 'Completed'), (4, 'Failed'), (99, 'Pending')], default=1)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('execute_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_tasks', to='automated_workflow.Node')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_tasks', to='automated_workflow.NodeRule')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('mode', models.IntegerField(choices=[(1, 'Disabled'), (2, 'Enabled')], default=1)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_nodes', to='automated_workflow.Workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='noderule',
            unique_together=set([('node', 'rule')]),
        ),
    ]
